name: Format, Build and Test


on:
    push:
        branches:
            - main

jobs:
    format-check:
        name: Formatting Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install clang-format
              run: sudo apt-get install clang-format

            - name: Run clang-format
              run: |
                clang-format --version
                find . -name "*.cpp" -o -name "*.h" | xargs clang-format -i
                git diff --exit-code
              continue-on-error: true # Don't stop the pipeline on error
    
    build:
        name: Build Project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential cmake libboost-all-dev  # Install Boost

            - name: Build project with CMake
              run: |
                mkdir -p build
                cd build
                cmake ..
                make
            
            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: build

    test:
        name: Run Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Download build artifacts
            uses: actions/download-artifact@v4
            with:
              name: build

          - name: Build for test
            run: |
              cd build
              cmake -DBUILD_TESTING=ON ..
              make
              ./cppwc_test
